from collections import Counter

import numpy as np

from qiskit import QuantumCircuit
from qiskit import qasm3
from qiskit.circuit.random import random_circuit
from qiskit.quantum_info import Statevector, state_fidelity

import json

from prompt_helper import PromptHelper

#NUM_QUBITS = 6
#DEPTH = 18
PATH = "universal_n10_l14_0-1.txt"

def main():
    # Option 2: Load a quantum circuit from a QASM file and analyze it
    # Load the QASM file
    # qc = QuantumCircuit.from_qasm_file("QFT8.qasm")
    qc = qasm3.load("universal_n10_l14_0.qasm")
    print_header("universal_n10_l14_0 Quantum Circuit:")
    print_text(qc)

    NUM_QUBITS = qc.num_qubits
    DEPTH = qc.depth()

    print_circuit_stats(qc)
    print_text(f"Number of qubits: {qc.num_qubits}")
    print_text(f"Circuit depth: {qc.depth()}")
    # End Option 2

    # Option 1: Generate a random quantum circuit and analyze it
    # Generate a random quantum circuit
    #qc = generate_random_circuit(
        #num_qubits=NUM_QUBITS,
        #depth=DEPTH,
    #)
    #print_header("Generated Random Quantum Circuit:")
    #print_text(qc)
    # End Option 1

    # Generate the statevector from the circuit
    state = compute_statevector(qc)
    print_header("State Vector:")
    print_text(array_to_string(state.data))

    # Compute measurement probabilities
    probabilities = compute_measurement_probabilities(state)
    measurement_probabilities = ""
    print_header("Measurement Probabilities:")
    for basis_state, probability in enumerate(probabilities):
        print_text(f"|{basis_state:0{NUM_QUBITS}b}>: {probability:.5f}")
        measurement_probabilities += f"  |{basis_state:0{NUM_QUBITS}b}>: {probability:.5f}\n"

    # Call LLM API to generate a quantum circuit based on the measurement probabilities
    prompt_helper = PromptHelper(num_qubits=NUM_QUBITS, depth=DEPTH)
    circuit_json = prompt_helper.execute_prompt(f"Target probability distribution:\n{measurement_probabilities}\n\nTarget state vector:\n{array_to_string(state.data)}")

    # print_header("LLM-Generated Circuit JSON:")
    # print_text(circuit_json)

    qc_llm = json_to_quantum_circuit(circuit_json)
    print_header("Quantum Circuit Generated by LLM:")
    print_text(qc_llm)

    print_circuit_stats(qc_llm)

    state_llm = compute_statevector(qc_llm)
    print_header("State Vector:")
    print_text(array_to_string(state_llm.data))

    probabilities_llm = compute_measurement_probabilities(state_llm)
    measurement_probabilities_llm = ""
    print_header("Measurement Probabilities from LLM-Generated Circuit:")
    for basis_state_llm, probability_llm in enumerate(probabilities_llm):
        print_text(f"|{basis_state_llm:0{NUM_QUBITS}b}>: {probability_llm:.5f}")
        measurement_probabilities_llm += f"  |{basis_state_llm:0{NUM_QUBITS}b}>: {probability_llm:.5f}\n"

    # Compute the fidelity between the states
    fidelity = compute_fidelity(state, state_llm)
    print_header("Fidelity of the state with the LLM-generated circuit:")
    print_text(f"{fidelity:.4f}")

    # Compute the diamond norm between the states
    # diamond_norm_var = diamond_norm(Choi(qc) - Choi(qc_llm))
    # print_header("Diamond norm between the original circuit and theLLM-generated circuit:")
    # print_text(f"{diamond_norm:.4f}")

    fidelity_new = fidelity
    # diamond_norm_var_new = diamond_norm_var
    state_llm_new = state_llm
    measurement_probabilities_new = measurement_probabilities_llm
    circuit_json_new = circuit_json
    i = 0
    while fidelity_new < 0.9 and i < 5:
        print_header(f"Fidelity is below 0.9, regenerating circuit (cycle {i+1}) ...")

        prompt = f"""
The previous circuit did not achieve high fidelity ({fidelity_new:.4f}). Generate a new circuit that better matches the target probability distribution, target state vector, and state fidelity.

Previous LLM-generated circuit:
{circuit_json_new}

Probability distribution from previous LLM-generated circuit:
{measurement_probabilities_new}

State vector from previous LLM-generated circuit:
{array_to_string(state_llm_new.data)}

Target probability distribution:
{measurement_probabilities}

Target state vector:
{array_to_string(state.data)}
"""

        circuit_json_new = prompt_helper.execute_prompt(prompt)
        qc_llm_new = json_to_quantum_circuit(circuit_json_new)
        print_header("Quantum Circuit Generated by LLM:")
        print_text(qc_llm_new)

        print_circuit_stats(qc_llm_new)

        state_llm_new = compute_statevector(qc_llm_new)
        print_header("State Vector from LLM-Generated Circuit:")
        print_text(array_to_string(state_llm_new.data))

        probabilities_new = compute_measurement_probabilities(state_llm_new)
        measurement_probabilities_new = ""
        print_header("Measurement Probabilities from LLM-Generated Circuit:")
        for basis_state_new, probability_new in enumerate(probabilities_new):
            print_text(f"|{basis_state_new:0{NUM_QUBITS}b}>: {probability_new:.5f}")
            measurement_probabilities_new += f"  |{basis_state_new:0{NUM_QUBITS}b}>: {probability_new:.5f}\n"

        fidelity_new = compute_fidelity(state, state_llm_new)
        print_header("Fidelity of the state with the new LLM-generated circuit:")
        print_text(f"{fidelity_new:.4f}")

        # diamond_norm_var_new = diamond_norm(Choi(qc) - Choi(qc_llm_new))
        # print_header("Diamond norm of the between the original circuit and the new LLM-generated circuit:")
        # print_text(f"{diamond_norm_var_new:.4f}")
        i += 1

def generate_random_circuit(num_qubits, depth):
    """Generates a random quantum circuit."""
    return random_circuit(num_qubits=num_qubits,
        depth=depth,
        max_operands=2,
        measure=False
    )

def compute_statevector(circuit: QuantumCircuit) -> Statevector: 
    """Computes the statevector from a quantum circuit."""
    return Statevector.from_instruction(circuit)

def compute_measurement_probabilities(statevector: Statevector) -> list:
    """Computes the measurement probabilities from a statevector."""
    return statevector.probabilities()

def compute_fidelity(statevector1: Statevector, statevector2: Statevector) -> float:
    """Computes the fidelity between two statevectors."""
    return state_fidelity(statevector1, statevector2)

def array_to_string(arr):
    return np.array2string(arr, threshold=np.inf, precision=6, separator=" ")

def json_to_quantum_circuit(json_string):

    data = json.loads(json_string)

    qc = QuantumCircuit(data["num_qubits"])

    operations = sorted(
        data["operations"],
        key=lambda op: op.get("layer", 0)
    )

    current_layer = None

    for op in operations:

        layer = op.get("layer", 0)

        # optional visual layer separation
        # if current_layer is not None and layer != current_layer:
        #     qc.barrier()

        current_layer = layer

        method_name = op["method"].lower()

        if not hasattr(qc, method_name):
            raise ValueError(f"Unsupported gate: {method_name}")

        method = getattr(qc, method_name)
        params = op.get("params", [])
        qubits = op.get("qubits", [])

        # Build the full argument list: numeric params first, then qubits.
        # Qiskit gate methods always take parameters before qubit specifiers.
        # e.g. qc.h(q0), qc.ry(theta, q0), qc.cx(control, target)
        try:
            if method_name in {"mcry", "mcrx", "mcrz", "mcp"}:
                angle = params[0]
                controls = qubits[:-1]
                target = qubits[-1]
                method(angle, controls, target)
            elif method_name in {"mcx"}:
                controls = qubits[:-1]
                target = qubits[-1]
                method(controls, target)
            else:
                method(*params, *qubits)
        except Exception as e:
            print(f"Warning: {method_name}({params}, {qubits}) failed: {e}.")
            print(json.dumps(data, indent=2))
            raise e
            
    return qc

def print_header(title):
    with open(PATH, "a", encoding="utf-8") as f:
        print("\n\n", file=f)
        print("---", file=f)
        print(f"{title}", file=f)
        print("---", file=f)
        print("\n", file=f)

def print_text(text):
    with open(PATH, "a", encoding="utf-8") as f:
        print(text, file=f)

def print_circuit_stats(qc):
    num_gates = qc.count_ops()
    total_gates = sum(num_gates.values())
    print_header("Circuit Statistics:")
    print_text(f"Total gates: {total_gates}")
    print_text(f"Gates: {list(num_gates.items())}")

    one_qubit_gates = 0
    two_qubit_gates = 0
    more_quibit_gates = 0

    for instruction in qc.data:

        operation = instruction.operation
        qargs = instruction.qubits

        num_qubits = len(qargs)

        if num_qubits == 1:
            one_qubit_gates += 1

        elif num_qubits == 2:
            two_qubit_gates += 1
        else:
            more_quibit_gates += 1

    print_text(f"1-qubit gates: {one_qubit_gates}")
    print_text(f"2-qubit gates: {two_qubit_gates}")
    print_text(f"n-qubit gates: {more_quibit_gates}")

if __name__ == "__main__":
    main()