import concurrent.futures
import os
from pathlib import Path

import numpy as np

from qiskit import QuantumCircuit, qasm3

from main import (
    compute_fidelity,
    compute_measurement_probabilities,
    compute_statevector,
    json_to_quantum_circuit,
    print_circuit_stats,
    print_header,
    print_text,
)
from prompt_helper import PromptHelper


QASM_FILES = [
    "../data/QFT5.qasm",
    "../data/QFT8.qasm",
    "../data/AA5.qasm",
    "../data/qec_en_n5.qasm",
    "../data/clifford_n5_l10_0.qasm",
    "../data/clifford_n8_l22_0.qasm",
    "../data/clifford_n10_l55_0.qasm",
    "../data/universal_n5_l10_0.qasm",
    "../data/universal_n8_l16_0.qasm",
    "../data/universal_n10_l14_0.qasm"
]
TRIES_PER_QASM = 5
MAX_WORKERS = int(os.getenv("QASM_MAX_WORKERS", "3"))


def qasm_output_path(qasm_path: str, try_number: int) -> str:
    return f"Q-{Path(qasm_path).stem}-{try_number}.txt"


def run_single_qasm_try(qasm_path: str, try_number: int) -> None:
    qasm_file = Path(qasm_path)
    qasm_name = qasm_file.stem
    output_path = qasm_output_path(qasm_path, try_number)

    if os.path.isfile(output_path) and os.path.getsize(output_path) > 0:
        print(f"Skipping {output_path} (already exists and is non-empty)")
        return

    # Reset/create file for this run.
    with open(output_path, "w", encoding="utf-8") as _f:
        _f.write("")

    # QASM 2.0
    qc = QuantumCircuit.from_qasm_file(str(qasm_file))
    # QASM 3.0
    # qc = qasm3.load(str(qasm_file))
    num_qubits = qc.num_qubits
    depth = qc.depth()

    print_header(f"Quantum Circuit from {qasm_file.name}:", output_path)
    print_text(qc, output_path)

    print_circuit_stats(qc, output_path)
    print_text(f"QASM file: {qasm_file.name}", output_path)
    print_text(f"QASM name: {qasm_name}", output_path)
    print_text(f"Try: {try_number}", output_path)
    print_text(f"Number of qubits: {num_qubits}", output_path)
    print_text(f"Circuit depth: {depth}", output_path)

    state = compute_statevector(qc)
    print_header("State Vector:", output_path)
    print_text(array_to_string(state.data), output_path)

    probabilities = compute_measurement_probabilities(state)
    measurement_probabilities = ""
    print_header("Measurement Probabilities:", output_path)
    for basis_state, probability in enumerate(probabilities):
        line = f"|{basis_state:0{num_qubits}b}>: {probability:.5f}"
        print_text(line, output_path)
        measurement_probabilities += f"  {line}\n"

    prompt_helper = PromptHelper(num_qubits=num_qubits, depth=depth)
    circuit_json = prompt_helper.execute_prompt(
        f"Target circuit source file: {qasm_file.name}\n\n"
        f"Target probability distribution:\n{measurement_probabilities}\n\n"
        f"Target state vector:\n{array_to_string(state.data)}"
    )

    if circuit_json is None:
        raise RuntimeError("LLM returned no response — check API connectivity and context window")

    qc_llm = json_to_quantum_circuit(circuit_json)

    print_header("Quantum Circuit Generated by LLM:", output_path)
    print_text(qc_llm, output_path)
    print_circuit_stats(qc_llm, output_path)

    state_llm = compute_statevector(qc_llm)
    print_header("State Vector from LLM-Generated Circuit:", output_path)
    print_text(array_to_string(state_llm.data), output_path)

    probabilities_llm = compute_measurement_probabilities(state_llm)
    measurement_probabilities_llm = ""
    print_header("Measurement Probabilities from LLM-Generated Circuit:", output_path)
    for basis_state_llm, probability_llm in enumerate(probabilities_llm):
        line = f"|{basis_state_llm:0{num_qubits}b}>: {probability_llm:.5f}"
        print_text(line, output_path)
        measurement_probabilities_llm += f"  {line}\n"

    fidelity = compute_fidelity(state, state_llm)
    print_header("Fidelity of the state with the LLM-generated circuit:", output_path)
    print_text(f"{fidelity:.4f}", output_path)

    fidelity_new = fidelity
    state_llm_new = state_llm
    measurement_probabilities_new = measurement_probabilities_llm
    circuit_json_new = circuit_json
    i = 0

    while fidelity_new < 0.9 and i < 5:
        print_header(
            f"Fidelity is below 0.9, regenerating circuit (cycle {i + 1}) ...",
            output_path,
        )

        prompt = f"""
The previous circuit did not achieve high fidelity ({fidelity_new:.4f}). Generate a new circuit that better matches the target probability distribution, target state vector, and state fidelity.

Previous LLM-generated circuit:
{circuit_json_new}

Probability distribution from previous LLM-generated circuit:
{measurement_probabilities_new}

State vector from previous LLM-generated circuit:
{array_to_string(state_llm_new.data)}

Target circuit source file:
{qasm_file.name}

Target probability distribution:
{measurement_probabilities}

Target state vector:
{array_to_string(state.data)}
"""

        circuit_json_new = prompt_helper.execute_prompt(prompt)

        if circuit_json_new is None:
            raise RuntimeError("LLM returned no response during retry — check API and context window")

        qc_llm_new = json_to_quantum_circuit(circuit_json_new)

        print_header("Quantum Circuit Generated by LLM:", output_path)
        print_text(qc_llm_new, output_path)
        print_circuit_stats(qc_llm_new, output_path)

        state_llm_new = compute_statevector(qc_llm_new)
        print_header("State Vector from LLM-Generated Circuit:", output_path)
        print_text(array_to_string(state_llm_new.data), output_path)

        probabilities_new = compute_measurement_probabilities(state_llm_new)
        measurement_probabilities_new = ""
        print_header("Measurement Probabilities from LLM-Generated Circuit:", output_path)
        for basis_state_new, probability_new in enumerate(probabilities_new):
            line = f"|{basis_state_new:0{num_qubits}b}>: {probability_new:.5f}"
            print_text(line, output_path)
            measurement_probabilities_new += f"  {line}\n"

        fidelity_new = compute_fidelity(state, state_llm_new)
        print_header("Fidelity of the state with the new LLM-generated circuit:", output_path)
        print_text(f"{fidelity_new:.4f}", output_path)
        i += 1

def array_to_string(arr):
    return np.array2string(arr, threshold=np.inf, precision=6, separator=" ")

def main() -> None:
    jobs = []
    skipped = 0
    for qasm_file in QASM_FILES:
        if not Path(qasm_file).is_file():
            raise FileNotFoundError(f"Missing QASM file: {qasm_file}")
        for try_number in range(1, TRIES_PER_QASM + 1):
            output_path = qasm_output_path(qasm_file, try_number)
            if os.path.isfile(output_path) and os.path.getsize(output_path) > 0:
                print(f"Skipping {output_path} (already exists and is non-empty)")
                skipped += 1
                continue
            jobs.append((qasm_file, try_number))

    print(
        f"Running {len(jobs)} QASM tries "
        f"({TRIES_PER_QASM} each for {', '.join(QASM_FILES)}; {skipped} skipped) "
        f"with {MAX_WORKERS} workers."
    )

    if not jobs:
        print("Nothing to run — all QASM output files already exist.")
        return

    with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {
            executor.submit(run_single_qasm_try, qasm_file, try_number): (
                qasm_file,
                try_number,
            )
            for qasm_file, try_number in jobs
        }
        for future in concurrent.futures.as_completed(futures):
            qasm_file, try_number = futures[future]
            output_path = qasm_output_path(qasm_file, try_number)
            try:
                future.result()
                print(f"Finished {output_path}")
            except Exception as exc:
                print(f"Error in {output_path}: {exc}")


if __name__ == "__main__":
    main()
